### ISSUE TITLE
다대일 양방향 연관관계 작성시 연관관계 편의 함수에 대한 의문점

### ISSUE THREAD

**Issue by readebooks** [holyeye/jpabook#3]
안녕하세요! 몇칠전 전자책을 구입해서 열심히 보고 있는 독자 입니다.
책을 보다 이해가 안되는 부분이 있어서 메일 보냅니다.

전자책 208쪽 다대일 양방향 연관관계에서...
연관관계 편의 함수 작성시

앞 장에서..Member.setTeam 메소드로 연관관계 변경시...
    @Entity
    public class Member {
        ...
        public void setTeam(Team team){
            if(this.team != null){
                this.team.getMembers().remove(this);
            }
            this.team = team;
            team.getMembers().add(this);
        }
    }
이전에 팀이 등록된 회원이라면 팀 엔티티에서도 회원 정보를 삭제하는것은 이해 했습니다.
회원이 팀을 바꾸는 거니깐 당연히 이전 팀에선 회원을 삭제해야 겠지요..

하지만 전자책 208쪽 다대일 양방향 연관관계에서...
왜 이전 팀에 등록된 회원 정보 삭제를 안하는 건지요?
    @Entity
    public class Member {
        ...
        public void setTeam(Team team){
            this.team = team;
            if(!team.getMembers().contains(this)){
                team.getMembers().add(this);
            }
        }
        ....
    }

   @Entity
   public class Team{
   ...
   public void addMember(Member member){
         ....
         this.members.add(member);
         if(member.getTeam() != this){
              member.setTeam(this);
          }
          ....
   }

**Comment by holyeye** [comment]
안녕하세요. @readebooks님
둘다 원칙적으로 삭제를 하는 것이 맞습니다.
그런데 이런 삭제 코드를 추가하는 것이 상당히 번거롭고, 다음에서 설명하는 내용 때문에 크게 문제가 되지 않기 때문입니다.
왜냐하면 보통 엔티티를 삭제하면 트랜잭션이 다 끝나버리고 HTTP 요청 및 응답도 다 끝나버린 상태가 됩니다.
이후에 다른 곳에서 다시 조회를 하면 데이터베이스에서 처음부터 다시 조회를 하게 되는데요. 이 경우에 조회를 해보면 이미 연관관계가 바뀐 상태로 조회가 되기 때문입니다.
데이터베이스에서 FK를 기준으로 연관된 데이터를 조회하는데, FK 자체가 이미 바뀌었기 때문에, 새로 조회할 때는 이 부분이 문제가 되지 않습니다.

물론 연관된 엔티티를 변경한 다음에 연결되어서 바로 연관된 객체들을 조작해야 한다면 remove()를 고려해야 합니다.
(하지만 실무에서는 보통 연관된 엔티티를 변경하고 로직이 끝나버립니다. 이후에 조회화면 같은 곳에서 다시 해당 엔티티를 조회하게 되는데, 이때는 앞서 설명드린 내용처럼 변경된 내용이 적용되어서 조회됩니다.)

감사합니다.
