### ISSUE TITLE
값 타입 컬렉션 ERD PK 의문점

### ISSUE THREAD

**Issue by Givebuff** [holyeye/jpabook#5]
안녕하세요.  책 구매 후 공부 중 의문점이 들어 한 가지 질문을 드려봅니다.

p.334의 코드를 일부 수정하여(**Set\<String>** favoriteFoods -> **List\<String>** favoriteFoods) 아래와 같이 데이터 저장 후 

![image](https://github.com/holyeye/jpabook/assets/29671762/0b21fa7d-0f22-4cb5-852b-fd2edda8da1d)

그림 9.8의 ERD를 보니 컬렉션 테이블의 모든 컬럼에 PK 제약 조건이 걸려 있는 걸 확인했습니다.

실제 테스트에선 중복된 값이 들어가도 별도의 오류를 나타내지 않고 잘 저장되는데

혹시 ERD의 PK 제약 조건은 어떤 의미의 PK인지 궁금합니다

**Comment by holyeye** [comment]
안녕하세요.
PK 제약조건이 모든 컬럼에 걸린다면 데이터베이스에 저장할 때 중복 값이 경우에는 오류가 발생하게 됩니다.
따라서 테스트 하신 경우 PK 제약조건이 걸리지 않은 것입니다.
JPA의 DDL 기능이 완벽하지 않기 때문에 이런 경우 직접 PK를 걸어주셔야 합니다.
감사합니다.
